<h1>Album Index pages</h1>

<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album_actions', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($data['albums'] as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title);?></td>
            <td><?php echo $this->escapeHtml($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url('album_actions',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                <a href="<?php echo $this->url('album_actions',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
