<?php
$title = 'Add album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

    <form action="<?= $this->url('album_actions', array('action' => 'add')) ?>" method="post">
         <input type="hidden" name="id"><br>
            <label>Title: </label><input type="text" name="title"><br>
            <label>Artist: </label><input type="text" name="artist"><br>
         <input type="submit" value="Add new album">
    </form>

<?php
//$form->setAttribute('action', $this->url('album_actions', array('action' => 'add')));
//$form->prepare();
//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('title')) . '<br>';
//echo $this->formRow($form->get('artist')) . '<br>';
//echo $this->formSubmit($form->get('submit')) . '<br>';
//echo $this->form()->closeTag();
//?>