<?php
$title = 'Add album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

    <form action="<?= $this->url('album_actions', array('action' => 'add')) ?>" method="post">
         <input type="hidden" name="id"><br>
        <div class="col-md-1">
            <label style="width: 100px; margin-bottom: 20px " >Title: </label> <br/>
            <label style="width: 100px; margin-bottom: 20px ">Artist: </label>
        </div>
        <div class="col-md-11">
            <input style="margin-bottom: 20px; width: 300px" type="text" name="title"><br />
            <input style="margin-bottom: 20px; width: 300px" type="text" name="artist">
        </div>
         <input type="submit" class="btn btn-success" value="Add new album">
    </form>

<?php
//$form->setAttribute('action', $this->url('album_actions', array('action' => 'add')));
//$form->prepare();
//echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('title')) . '<br>';
//echo $this->formRow($form->get('artist')) . '<br>';
//echo $this->formSubmit($form->get('submit')) . '<br>';
//echo $this->form()->closeTag();
//?>