<?php
$title = 'Edit album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <form action="<?= $this->url('album_actions', array('action' => 'edit')) ?>" method="post">
        <input type="hidden" name="id" value="<?php echo $this->escapeHtml($data['album']->id);?>"><br>
        <div class="col-md-1">
            <label style="width: 100px; margin-bottom: 20px " >Title: </label> <br/>
            <label style="width: 100px; margin-bottom: 20px ">Artist: </label>
        </div>
        <div class="col-md-11">
            <input style="margin-bottom: 20px; width: 300px" type="text" name="title" value="<?php echo $this->escapeHtml($data['album']->title);?>"><br />
            <input style="margin-bottom: 20px; width: 300px" type="text" name="artist" value="<?php echo $this->escapeHtml($data['album']->artist);?>">
        </div>
        <input type="submit" class="btn btn-success" value="Update">
    </form>